spring.application.name=droneserver

# Render / Deploy
server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1

# BASE DE DATOS ONLINE RAILWAY
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# IMPRIME LOS ERRORES 
server.error.include-message=always
server.error.include-binding-errors=always
